require("catppuccin").setup({
    transparent_background = false,
    color_overrides = {
      all = {
          text = "#ffffff",
      },
      mocha = {
          base = "#181825",
      },
      frappe = {},
      macchiato = {},
      latte = {},
    },
    integrations = {
	  treesitter = true,
	  native_lsp = {
        enabled = true,
        virtual_text = {
   	    errors = { "italic" },
   	    hints = { "italic" },
   	    warnings = { "italic" },
   	    information = { "italic" },
      },
      underlines = {
   	    errors = { "underline" },
   	    hints = { "underline" },
   	    warnings = { "underline" },
   	    information = { "underline" },
      },
    },
    coc_nvim = false,
    lsp_trouble = false,
    cmp = true,
    lsp_saga = false,
    gitgutter = false,
    gitsigns = false,
    telescope = true,
    nvimtree = false,
    dap = {
   	  enabled = false,
   	  enable_ui = false,
    },
    neotree = {
   	  enabled = false,
   	  show_root = true,
   	  transparent_panel = false,
    },
    which_key = false,
    indent_blankline = {
   	  enabled = true,
   	  colored_indent_levels = false,
    },
    dashboard = false,
    neogit = false,
    vim_sneak = false,
    fern = false,
    barbar = false,
    markdown = true,
    lightspeed = false,
    leap = false,
    ts_rainbow = false,
    hop = false,
    notify = false,
    telekasten = false,
    symbols_outline = false,
    mini = false,
    aerial = false,
    vimwiki = false,
    beacon = false,
    overseer = false,
    fidget = false,
    treesitter_context = false,
  },
  custom_highlights = function(C)
	return {
	  CmpItemKindSnippet = { fg = C.mauve },
	  CmpItemKindKeyword = { fg = C.red },
	  CmpItemKindText = { fg = C.teal },
	  CmpItemKindMethod = { fg = C.blue },
	  CmpItemKindConstructor = { fg = C.blue },
	  CmpItemKindFunction = { fg = C.blue },
	  CmpItemKindFolder = { fg = C.blue },
	  CmpItemKindModule = { fg = C.blue },
	  CmpItemKindConstant = { fg = C.peach },
	  CmpItemKindField = { fg = C.green },
	  CmpItemKindProperty = { fg = C.green },
	  CmpItemKindEnum = { fg = C.green },
	  CmpItemKindUnit = { fg = C.green },
	  CmpItemKindClass = { fg = C.yellow },
	  CmpItemKindVariable = { fg = C.flamingo },
	  CmpItemKindFile = { fg = C.blue },
	  CmpItemKindInterface = { fg = C.yellow },
	  CmpItemKindColor = { fg = C.red },
	  CmpItemKindReference = { fg = C.red },
	  CmpItemKindEnumMember = { fg = C.red },
	  CmpItemKindStruct = { fg = C.blue },
	  CmpItemKindValue = { fg = C.peach },
	  CmpItemKindEvent = { fg = C.blue },
	  CmpItemKindOperator = { fg = C.blue },
	  CmpItemKindTypeParameter = { fg = C.blue },
	  CmpItemKindCopilot = { fg = C.teal },
	}
  end,
})
