require("catppuccin").setup({
    color_overrides = {
        all = {
            text = "#ffffff",
        },
        mocha = {
            base = "#1e1e2e",
        },
        frappe = {},
        macchiato = {},
        latte = {},
    },
    integrations = {
	  treesitter = true,
	  native_lsp = {
        enabled = true,
        virtual_text = {
   	    errors = { "italic" },
   	    hints = { "italic" },
   	    warnings = { "italic" },
   	    information = { "italic" },
      },
      underlines = {
   	    errors = { "underline" },
   	    hints = { "underline" },
   	    warnings = { "underline" },
   	    information = { "underline" },
      },
    },
    coc_nvim = false,
    lsp_trouble = false,
    cmp = true,
    lsp_saga = true,
    gitgutter = false,
    gitsigns = false,
    telescope = true,
    nvimtree = false,
    dap = {
   	  enabled = false,
   	  enable_ui = false,
    },
    neotree = {
   	  enabled = false,
   	  show_root = true,
   	  transparent_panel = false,
    },
    which_key = false,
    indent_blankline = {
   	  enabled = true,
   	  colored_indent_levels = false,
    },
    dashboard = false,
    neogit = false,
    vim_sneak = false,
    fern = false,
    barbar = false,
    markdown = true,
    lightspeed = false,
    leap = false,
    ts_rainbow = false,
    hop = false,
    notify = true,
    telekasten = false,
    symbols_outline = false,
    mini = false,
    aerial = false,
    vimwiki = false,
    beacon = false,
    overseer = false,
    fidget = true,
    treesitter_context = false,
  },
  custom_highlights = {}
})
