#! /bin/sh

##################################################################################################################
#AUTOSTART
##################################################################################################################
killall sxhkd
sxhkd &
nm-applet &
killall thunar
thunar --daemon &
killall lxsession
lxsession &
picom &
killall emacs
emacs --daemon &
feh --randomize --bg-fill ~/wallpapers/* &
/home/jay/.config/polybar/launch.sh &
betterlockscreen -u /home/jay/wallpapers &

##################################################################################################################
#SETTINGS
##################################################################################################################
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

##################################################################################################################
#THEMING
##################################################################################################################
bspc config normal_border_color "#434758"
bspc config active_border_color "#82aaff"
bspc config focused_border_color "#82aaff"
bspc config presel_feedback_color "#9cc5ff"

bspc config border_width         2
bspc config window_gap          10
bspc config top_padding         27
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

##################################################################################################################
#WINDOW RULES
##################################################################################################################
bspc rule -a Brave-browser desktop='^1'
bspc rule -a qutebrowser desktop='^1'
bspc rule -a Spotify desktop='^3'
bspc rule -a qBittorrent desktop='^7'
bspc rule -a Lxpolkit state=floating
bspc rule -a Emacs state=tiled
