#! /bin/sh

##################################################################################################################
#AUTOSTART
##################################################################################################################
killall sxhkd
sxhkd &
nm-applet &
feh --randomize --bg-fill ~/wallpapers/* &
thunar --daemon &
lxsession &
/home/jay/.config/polybar/launch.sh &

##################################################################################################################
#SETTINGS
##################################################################################################################
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

##################################################################################################################
#THEMING
##################################################################################################################
bspc config normal_border_color "#D0D0D0"
bspc config active_border_color "#82AAFF"
bspc config focused_border_color "#82AAFF"
bspc config presel_feedback_color "#9CC5FF"

bspc config border_width         2
bspc config window_gap          10
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

##################################################################################################################
#WINDOW RULES
##################################################################################################################
bspc rule -a firefoxdeveloperedition desktop='^1'
bspc rule -a qBittorrent desktop='^7'
bspc rule -a discord desktop='^6'
bspc rule -a Emacs state=tiled
