#! /bin/sh

##################################################################################################################
#AUTOSTART
##################################################################################################################
killall sxhkd
sxhkd &
killall volumeicon
nm-applet &
volumeicon &
killall thunar
thunar --daemon &
killall lxsession
lxsession &
picom --experimental-backends &
emacs --daemon &
feh --randomize --bg-fill ~/wallpapers/* &
/home/jay/.config/polybar/launch.sh &


##################################################################################################################
#SETTINGS
##################################################################################################################
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

##################################################################################################################
#THEMING
##################################################################################################################
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config border_width         2
bspc config window_gap          10
bspc config top_padding         29
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

##################################################################################################################
#WINDOW RULES
##################################################################################################################
bspc rule -a Brave-browser desktop='^1'
bspc rule -a Lxpolkit state=floating
bspc rule -a Emacs state=tiled
