version = 3
final_space = true

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '[{{ .CurrentDate | date .Format }}]'
    foreground = '#E5C07B'
    type = 'time'
    style = 'plain'

    [blocks.segments.properties]
      time_format = '15:04'

  [[blocks.segments]]
    template = '  {{ .Name }}'
    foreground = '#E06C75'
    type = 'shell'
    style = 'plain'

    [blocks.segments.properties]
      [blocks.segments.properties.mapped_shell_names]
        bash = 'Bash'
        cmd = 'Cmd'
        powershell = 'Shell'
        pwsh = 'Shell'

  [[blocks.segments]]
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#F3C267'
    type = 'git'
    style = 'plain'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}', '{{ if gt .Ahead 0 }}#B388FF{{ end }}', '{{ if gt .Behind 0 }}#B388FF{{ end }}']

    [blocks.segments.properties]
      branch_template = '{{ trunc 25 .Branch }}'
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = ' x{{ reason .Code }}'
    foreground = '#b8ff75'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#E06C75{{ end }}']

  [[blocks.segments]]
    template = ' {{ .FormattedMs }} '
    foreground = '#b8ff75'
    type = 'executiontime'
    style = 'diamond'
    foreground_templates = ['{{ if gt .Code 0 }}#E06C75{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      style = 'roundrock'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ' {{ .Path }}'
    foreground = '#61AFEF'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '!'
    foreground = '#E06C75'
    type = 'root'
    style = 'plain'

  [[blocks.segments]]
    template = '❯'
    foreground = '#E06C75'
    type = 'text'
    style = 'plain'
